apiVersion: v1
kind: Service
metadata:
  name: formix-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: formix-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: formix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formix-app
  template:
    metadata:
      labels:
        app: formix-app
    spec:
      containers:
      - image: formix-app:latest
        name: formix-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_DATABASE
          value: formix
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: root
