apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- app-deployment.yaml
- mysql-deployment.yaml

configMapGenerator:
- name: mysql-init-script
  files:
  - init.sql=../docker/init.sql
